import GlitchText from '@/components/GlitchText';
import Head from 'next/head';
import { Canvas, useFrame, useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { Suspense, useState } from 'react';
import { OrbitControls } from '@react-three/drei';

const Tablet = () => {
  const tablet = useLoader(GLTFLoader, '/tablet.gltf');

  return (
    <>
      <primitive object={tablet.scene} />
    </>
  );
};

const Room = () => {
  const room = useLoader(GLTFLoader, '/room.gltf');
  room.scene.castShadow = true;

  return (
    <>
      <primitive object={room.scene} />
    </>
  );
};

const BlinkingLight = () => {
  const [redLightIntensity, setRedLightIntensity] = useState(0);

  useFrame(() => {
    setRedLightIntensity(Number(Math.random().toFixed(1)));
  });

  return (
    <pointLight
      color={[1, 0, 0]}
      intensity={redLightIntensity}
      position={[-10, -4, 4]}
      castShadow
    />
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Theresa Baumgartner</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Canvas style={{ position: 'absolute', height: '100vh' }}>
        <Suspense fallback={null}>
          <Room />
          <OrbitControls />
          {/* <directionalLight intensity={1} position={[0, 3, 0]} castShadow /> */}
          <BlinkingLight />
        </Suspense>
      </Canvas>
      <main>
        <div className='flex h-[100vh] w-full items-center justify-center'>
          <div className='w-96'></div>
        </div>
      </main>
    </>
  );
}
